// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://upkdlgsvbnwzxfmqbena.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwa2RsZ3N2Ym53enhmbXFiZW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwOTk1MTQsImV4cCI6MjA4NzY3NTUxNH0.Wgk-IteD_uB0dEcssMj8EOgBTKtWtL6CU0jAGOECrws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});